### ISSUE TITLE
Individual map stats missing for some players 

### ISSUE THREAD

**Issue by paulhicks91** [dperelman/kqb-stats-viewer#2]
The stats are missing for some players on some maps. I think the issue is due to mid-game/mid-match entries/drops. I've attached a screenshot below. You can see that there are 8 players on blue and 5 players on gold which is not normal so this is definitely an edge case in the context of BGL/Ranked games. QP and Customs are most likely to be affected by this issue.

![Missing stats](https://user-images.githubusercontent.com/42584788/136720854-65f6d8db-f395-4536-8361-e0a1da6f2080.png)

Here's the raw stats in a txt file (GitHub won't let me upload a JSON file):  [Unranked-2021-10-09-11-22-01.txt](https://github.com/dperelman/kqb-stats-viewer/files/7318926/Unranked-2021-10-09-11-22-01.txt)

**Comment by dperelman** [comment]
d4ca9a5dbf5fda6aa4bce6609162e02951e753d9 fixes this bug. Thanks for the bug report.
